---
title: "Verbrauch der Kornkammer"
author: "Kornkammer e.V."
date: "November 13, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Verbrauch von Nudeln (grafisch)


Der visualisierte Verbrauch von Nudeln der Kornkammer bis September 2017:

```{r, echo=c(1,1e3,14,15,16,17,18), message=FALSE}
library(ggplot2)
library(lubridate)
data("kornumsatz_new", package = "foodstorage")
starting_csv <<- read.csv("/home/simon/Documents/Studium/Bachelor-Arbeit/R-paket/foodstorage/data/starting_csv_20171125.csv")
# '<<-' important because kornumsatz must be in globalenv() that it can be found by functions in server UI
kornumsatz <- kornumsatz_new
kornumsatz$Produkt <- as.character(kornumsatz$Produkt) 
# print(length(unique(kornumsatz$Produkt)))
kornumsatz <- foodstorage::startup.settings(kornumsatz, importPRODUCTS = starting_csv)
# print(length(unique(kornumsatz$Produkt)))
# print(starting_csv)
kornumsatz$Produkt <- as.factor(kornumsatz$Produkt)
nudeln.typen <- c("Nudeln Dinkel", 
                  "Nudeln vom Grosshandel", 
                  "Spaghetti Dinkel", 
                  "Spaghetti vom Grosshandel")
nudeln <- foodstorage::currentStorage(nudeln.typen, 
                                      rawlist = T, 
                                      order.storage = F, 
                                      result = "result")[c("Tag", 
                                                           "Bestand.Einheit", 
                                                           "Produkt")]
foodstorage::plotgg(nudeln)
```

## Verbrauch aller Lebensmittel (tabelarisch)

Und hier zur Übersicht noch alle anderen Produkte in Zahlen:

```{r, echo=T, message=FALSE}
allproducts <- as.character(levels(kornumsatz$Produkt))
foodstorage::currentStorage(allproducts, 
                            order.storage = FALSE, 
                            rawlist = TRUE, 
                            result = "shopping")
```